# Blog settings
permalink: /blog/:title

baseurl: /

# My variables
name: TS
description: web developer, wordpress expert, woocomomerce expert, super heroes enthusiast
google_verification: 4M49-XV-qfwCTBmX3hS6y8ld0sdThWuSVtnyAW0vDRE


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    comments: "true"
    layout: "post"
-
  scope:
    path: ""
    type: "posts"
  values:
    featured: "false"
    layout: "post"
-
  scope:
    path: ""
    type: "posts"
  values:
    ext_url: ""
    
gems:
  - jekyll-gist
  - jekyll-seo-tag
